# Generated by Django 5.1.3 on 2024-11-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityCategoryDimension',
            fields=[
                ('charity_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DateDimension',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_date', models.DateField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('day_of_week', models.CharField(max_length=10)),
                ('is_weekend', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategoryDimension',
            fields=[
                ('service_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTypeDimension',
            fields=[
                ('transaction_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserDemographicsDimension',
            fields=[
                ('user_demographics_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age_group', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CharityDimension',
            fields=[
                ('charity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charity_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl_app.charitycategorydimension')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDimension',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=50)),
                ('service_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl_app.servicecategorydimension')),
            ],
        ),
        migrations.CreateModel(
            name='UserDimension',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField()),
                ('phone_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_admin', models.BooleanField()),
                ('user_demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl_app.userdemographicsdimension')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionFact',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('charity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etl_app.charitydimension')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl_app.datedimension')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etl_app.servicedimension')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl_app.transactiontypedimension')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl_app.userdimension')),
            ],
        ),
    ]
