# Generated by Django 5.1.3 on 2024-11-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitycategorydimension',
            name='charity_category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='charitydimension',
            name='charity_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datedimension',
            name='date_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicecategorydimension',
            name='service_category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicedimension',
            name='service_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionfact',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactiontypedimension',
            name='transaction_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdemographicsdimension',
            name='user_demographics_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdimension',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userdimension',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdimension',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
