# Generated by Django 5.1.3 on 2024-11-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0003_remove_datedimension_is_weekend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datedimension',
            name='full_date',
        ),
        migrations.RemoveField(
            model_name='transactionfact',
            name='timestamp',
        ),
    ]
